:awestruct-layout: base
:showtitle:
:prev_section: defining-frontmatter
:next_section: creating-pages
:toc: macro 
toc::[] 

= Introduction (H1)
This project uses Quarkus, the Supersonic Subatomic Java Framework.
If you want to learn more about Quarkus, please visit its website: https://quarkus.io/ .

= Steps and details (H1)

== Running the application in dev mode (H2)

You can run your application in dev mode that enables live coding using:
```
./mvnw quarkus:dev
```
[source,bash]
----
./mvnw quarkus:dev
----

== Packaging and running the application (H2)

The application is packageable using `./mvnw package`.
It produces the executable `serverless-demo-1.0.0-SNAPSHOT-runner.jar` file in `/target` directory.
Be aware that it’s not an _über-jar_ as the dependencies are copied into the `target/lib` directory.

The application is now runnable using `java -jar target/serverless-demo-1.0.0-SNAPSHOT-runner.jar`.

== Creating an executable (H2)

=== Native executable (H3)
You can create a native executable using: `./mvnw package -Pnative`.

=== Docker executable (H3)
Or you can use Docker to build the native executable using: `./mvnw package -Pnative -Dquarkus.native.container-build=true`.
You can then execute your binary: `./target/serverless-demo-1.0.0-SNAPSHOT-runner`
